# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
#
# All official lint rules are documented at
# https://dart.dev/tools/linter-rules

include: package:very_good_analysis/analysis_options.5.1.0.yaml

analyzer:
  exclude:
    - examples/**

linter:
  rules:
    sort_pub_dependencies: false