include: package:very_good_analysis/analysis_options.10.0.0.yaml

plugins:
  nilts:
    path: packages/nilts
  nilts_clock:
    path: packages/nilts_clock
  nilts_flutter_hooks:
    path: packages/nilts_flutter_hooks

analyzer:
  exclude:
    - packages/*/lib/analysis_options.yaml

linter:
  rules:
    sort_pub_dependencies: false

formatter:
  trailing_commas: preserve
