name: nilts

repository:
  type: github
  origin: https://github.com/dassssshers/nilts
  owner: ronnnnn
  name: nilts

packages:
  - .
  - packages/**
  - examples/**

ide:
  intellij: true

command:
  bootstrap:
    enforceLockfile: true

  version:
    message: |
      release: publish packages

      {new_package_versions}
    includeCommitId: true
    changelogs:
      - path: packages/nilts/CHANGELOG.md
        description: |
          All notable changes to nilts packages will be documented in this file.
        packageFilters:
          scope: nilts
    releaseUrl: true

scripts:
  prepare:
    run: |
      dart pub global activate custom_lint 0.7.2 && \
      dart pub global activate very_good_cli 0.25.0
    description: prepare for develop

  get:
    run: melos exec -c 1 --fail-fast -- flutter pub get
    description: pub get

  lint:
    run: |
      melos lint:dart && \
      melos lint:flutter && \
      melos lint:custom_lint
    description: lint

  lint:dart:
    run: melos exec -c 1 --scope="nilts" -- dart analyze --fatal-infos --fatal-warnings
    description: lint with dart

  lint:flutter:
    run: melos exec -c 1 --scope="nilts_test" -- flutter analyze --fatal-infos --fatal-warnings
    description: lint with flutter

  lint:custom_lint:
    run: melos exec -c 1 --scope="nilts_test" -- flutter pub run custom_lint
    description: lint with custom_lint

  fmt:
    run: |
      melos fix && \
      melos fmt:dart
    description: format

  fmt:dry:
    run: |
      melos fix:dry && \
      melos fmt:dart:dry
    description: format (dry-run)

  fmt:dart:
    # https://github.com/dart-lang/sdk/issues/59815
    run: melos exec -c 1 --fail-fast -- dart format --enable-experiment=digit-separators .
    description: format dart

  fmt:dart:dry:
    # https://github.com/dart-lang/sdk/issues/59815
    run: melos exec -c 1 --fail-fast -- dart format --set-exit-if-changed --enable-experiment=digit-separators .
    description: format dart (dry-run)

  fix:
    run: melos exec -c 1 --fail-fast -- dart fix --apply
    description: fix dart

  fix:dry:
    run: melos exec -c 1 --fail-fast -- dart fix --dry-run
    description: fix dart (dry-run)

  test:
    exec: very_good test
    packageFilters:
      scope: nilts_test
    description: test on nilts_test

  build:example:
    run: |
      melos build:example:android && \
      melos build:example:ios
    description: build on nilts_example

  build:example:android:
    run: melos exec -c 1 --scope="nilts_example" -- flutter build appbundle
    description: build android on nilts_example

  build:example:ios:
    run: melos exec -c 1 --scope="nilts_example" -- flutter build ios --no-codesign
    description: build ios on nilts_example
