name: nilts

repository:
  type: github
  origin: https://github.com/ronnnnn/nilts
  owner: ronnnnn
  name: nilts

packages:
  - packages/**
  - examples/**

ide:
  intellij: true
  vscode: true

command:
  bootstrap:
    enforceLockfile: true

  version:
    message: |
      release: publish packages
      
      {new_package_versions}
    includeCommitId: true
    changelogs:
      - path: packages/nilts/CHANGELOG.md
        description: |
          All notable changes to nilts packages will be documented in this file.
        packageFilters:
          scope: nilts
    releaseUrl: true

scripts:
  prepare:
    run: |
      dart pub global activate custom_lint 0.6.0
    description: install custom_lint

  get:
    run: |
      melos exec -- "flutter pub get"
    description: flutter pub get

  analyze:
    run: |
      melos analyze:flutter
      melos analyze:dart
    description: melos analyze:flutter && melos analyze:dart

  analyze:flutter:
    run: |
      melos exec -- "flutter analyze --fatal-infos --fatal-warnings"
      melos exec -- "flutter pub run custom_lint"
    packageFilters:
      flutter: true
    description: flutter analyze --fatal-infos --fatal-warnings

  analyze:dart:
    run: |
      melos exec -- "dart analyze --fatal-infos --fatal-warnings"
    packageFilters:
      scope: nilts
    description: dart analyze --fatal-infos --fatal-warnings

  pretty:
    run: |
      melos fix
      melos format
    description: melos fix && melos format

  pretty:check:
    run: |
      melos fix:check
      melos format:check
    description: melos fix:check && melos format:check

  format:
    run: |
      melos exec -- "dart format ."
    description: dart format .

  format:check:
    run: |
      melos exec -- "dart format --set-exit-if-changed ."
    description: dart format --set-exit-if-changed .

  fix:
    run: |
      melos exec -- "dart fix --apply"
    description: dart fix --apply

  fix:check:
    run: |
      melos exec -- "dart fix --dry-run"
    description: dart fix --dry-run

  test:
    run: |
      melos format:check
      melos exec -- "flutter analyze --fatal-infos --fatal-warnings"
      melos exec -- "flutter pub run custom_lint"
      melos exec -- "flutter test"
    packageFilters:
      scope: nilts_test
    description: test on nilts_test

  build:example:
    run: |
      melos build:example:android && melos build:example:ios
    packageFilters:
      scope: nilts_example
    description: build on nilts_example

  build:example:android:
    run: |
      melos exec -- "flutter build appbundle"
    packageFilters:
      scope: nilts_example
    description: build android on nilts_example

  build:example:ios:
    run: |
      melos exec -- "flutter build ios --no-codesign"
    packageFilters:
      scope: nilts_example
    description: build ios on nilts_example
