name: nilts

repository:
  type: github
  origin: https://github.com/ronnnnn/nilts
  owner: ronnnnn
  name: nilts

packages:
  - .
  - packages/**
  - examples/**

ide:
  intellij: true
  vscode: true

command:
  bootstrap:
    enforceLockfile: true

  version:
    message: |
      release: publish packages
      
      {new_package_versions}
    includeCommitId: true
    changelogs:
      - path: packages/nilts/CHANGELOG.md
        description: |
          All notable changes to nilts packages will be documented in this file.
        packageFilters:
          scope: nilts
    releaseUrl: true

scripts:
  prepare:
    run: |
      dart pub global activate custom_lint 0.6.0 && \
      dart pub global activate very_good_cli 0.22.1
    description: prepare for develop

  get:
    run: melos exec -c 1 -- flutter pub get
    description: pub get

  check:
    steps:
      - check:dart
      - check:flutter
      - check:custom_lint
    description: check static analysis

  check:dart:
    run: melos exec -c 1 --scope="nilts" -- dart analyze --fatal-infos --fatal-warnings
    description: check static analysis for dart

  check:flutter:
    run: melos exec -c 1 --scope="nilts_test" -- flutter analyze --fatal-infos --fatal-warnings
    description: check static analysis for flutter

  check:custom_lint:
    run: melos exec -c 1 --scope="nilts_test" -- flutter pub run custom_lint
    description: check static analysis with custom_lint

  pretty:
    steps:
      - fix
      - pretty:dart
    description: format

  pretty:dry:
    steps:
      - fix:dry
      - pretty:dart:dry
    description: format (dry-run)

  pretty:dart:
    run: melos exec -c 1 -- dart format .
    description: format dart

  pretty:dart:dry:
    run: melos exec -c 1 -- dart format --set-exit-if-changed .
    description: format dart (dry-run)

  fix:
    run: melos exec -c 1 -- dart fix --apply
    description: fix dart

  fix:dry:
    run: melos exec -c 1 -- dart fix --dry-run
    description: fix dart (dry-run)

  test:
    exec: very_good test
    packageFilters:
      scope: nilts_test
    description: test on nilts_test

  build:example:
    steps:
      - build:example:android
      - build:example:ios
    description: build on nilts_example

  build:example:android:
    run: melos exec -c 1 --scope="nilts_example" -- flutter build appbundle
    description: build android on nilts_example

  build:example:ios:
    run: melos exec -c 1 --scope="nilts_example" -- flutter build ios --no-codesign
    description: build ios on nilts_example
