import 'package:custom_lint_builder/custom_lint_builder.dart';
import 'package:nilts_clock/src/lints/using_date_time_now.dart';

/// custom_lint integrates the nilts's plugin from this method on
/// `custom_lint_client.dart` which is generated by custom_lint CLI.
PluginBase createPlugin() => _NiltsClockLint();

/// A class for defining all lint rules and assists
/// managed by nilts_clock.
class _NiltsClockLint extends PluginBase {
  @override
  List<LintRule> getLintRules(CustomLintConfigs configs) => [
        const UsingDateTimeNow(),
      ];
}
