name: nilts_test
description: A new Flutter module project.
publish_to: 'none'

environment:
  sdk: '>=3.7.0 <4.0.0'
  flutter: '>=3.29.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  custom_lint: 0.7.5
  very_good_analysis: 7.0.0

  nilts:
    path: ../nilts

flutter:
  uses-material-design: true
