name: nilts_test
description: A new Flutter module project.
publish_to: 'none'

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.22.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  custom_lint: ^0.6.4

  nilts:
    path: ../nilts

flutter:
  uses-material-design: true
