name: nilts_test
description: A new Flutter module project.
publish_to: 'none'

environment:
  sdk: '>=3.9.2 <4.0.0'
  flutter: '>=3.35.3'

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  clock: 1.1.2
  flutter_hooks: 0.21.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  custom_lint: 0.8.0
  very_good_analysis: 9.0.0

flutter:
  uses-material-design: true
