name: nilts_test
description: A new Flutter module project.
publish_to: 'none'

environment:
  sdk: '>=3.8.1 <4.0.0'
  flutter: '>=3.32.1'

dependencies:
  flutter:
    sdk: flutter

  clock: 1.1.2
  flutter_hooks: 0.21.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  custom_lint: 0.7.5
  very_good_analysis: 8.0.0

  nilts:
    path: ../nilts
  nilts_clock:
    path: ../nilts_clock
  nilts_flutter_hooks:
    path: ../nilts_flutter_hooks

flutter:
  uses-material-design: true
