name: Bug report for an existing lint rule, quick fix or assists.
description: Report bug details you found and describe clearly as possible.
title: '[Bug]: Title of the bug'
labels: ['bug']
assignees: ['@ronnnnn']
body:
  - type: dropdown
    attributes:
      label: Which feature types the bug belongs to?
      description: Please select one or more types from belows.
      multiple: true
      options:
        - Lint Rule
        - Quick fix
        - Assist
        - Other (Docs, CI, etc...)
    validations:
      required: true
  - type: textarea
    attributes:
      label: Bug overview
      description: Please tell me summary of the bug.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps reproduce
      description: Describe how to reproduce the bug step by step.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected result
      description: Describe expected behavior.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Actual result
      description: Describe current behavior.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Affected version
      description: Which version of nilts you use.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Flutter doctor
      description: Copy and paste here, `flutter doctor` output.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional context
      description: Describe additional context if you have.
    validations:
      required: false
