import 'package:custom_lint_builder/custom_lint_builder.dart';
import 'package:nilts_flutter_hooks/src/lints/unnecessary_hook_widget.dart';

/// custom_lint integrates the nilts's plugin from this method on
/// `custom_lint_client.dart` which is generated by custom_lint CLI.
PluginBase createPlugin() => _NiltsFlutterHooksLint();

/// A class for defining all lint rules and assists
/// managed by nilts_flutter_hooks.
class _NiltsFlutterHooksLint extends PluginBase {
  @override
  List<LintRule> getLintRules(CustomLintConfigs configs) => [
        const UnnecessaryHookWidget(),
      ];
}
