name: Setup Java 🔧
description: Download and cache tools for Java

runs:
  using: 'composite'
  steps:
    - name: Import .tool-versions
      uses: wasabeef/import-asdf-tool-versions-action@d0271ba3d7b75e5861889c6923e898190e3a7383 # v1.1.0
      id: asdf
    - name: Extract distribution and version
      id: extract_distribution_and_version
      shell: bash
      run: |
        java=${{ steps.asdf.outputs.java }}
        echo "distribution=$(echo $java | cut -d '-' -f 1)" >> $GITHUB_OUTPUT
        echo "version=$(echo $java | cut -d '-' -f 2)" >> $GITHUB_OUTPUT
    - uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5
      with:
        distribution: ${{ steps.extract_distribution_and_version.outputs.distribution }}
        java-version: ${{ steps.extract_distribution_and_version.outputs.version }}
        cache: 'gradle'
