name: Setup Dart & Flutter 🔧
description: Download and cache tools for Dart & Flutter

runs:
  using: 'composite'
  steps:
    - name: Extract tool versions from .tool-versions
      uses: wasabeef/import-asdf-tool-versions-action@d0271ba3d7b75e5861889c6923e898190e3a7383 # v1.1.0
      id: versions
    - name: Download and cache Flutter SDK
      uses: subosito/flutter-action@e938fdf56512cc96ef2f93601a5a40bde3801046 # v2.19.0
      with:
        channel: stable
        flutter-version: ${{ steps.versions.outputs.flutter }}
        cache: true
    - name: Extract Melos version from pubspec
      id: version
      uses: pietrobolcato/action-read-yaml@9f13718d61111b69f30ab4ac683e67a56d254e1d # v1.1.0
      with:
        config: ./pubspec.yaml
    - name: Download Melos and bootstrap
      uses: bluefireteam/melos-action@b3ccbb59dd75a6c926d54684abd8c5cda074457a # v3
      with:
        melos-version: ${{ steps.version.outputs.outputs['dev_dependencies']['melos'] }}
        run-bootstrap: true
    - name: Install others
      shell: bash
      run: melos prepare
