name: Setup Dart & Flutter 🔧
description: Download and cache tools for Dart & Flutter

runs:
  using: 'composite'
  steps:
    - name: Extract tool versions from .tool-versions
      uses: wasabeef/import-asdf-tool-versions-action@396ae6da83370122ec5fbcc4b5fc994239b214b6 # v1.0.1
      id: versions
    - name: Download and cache Flutter SDK
      uses: subosito/flutter-action@48cafc24713cca54bbe03cdc3a423187d413aafa # v2.10.0
      with:
        channel: stable
        flutter-version: ${{ steps.versions.outputs.flutter }}
        cache: true
    - name: Extract Melos version from pubspec
      id: melos
      uses: mikefarah/yq@dd648994340a5d03225d97abf19c9bf1086c3f07 # v4.40.5
      with:
        cmd: yq '.dev_dependencies.melos' './pubspec.yaml'
    - name: Download Melos and bootstrap
      uses: bluefireteam/melos-action@334ecf69189b746dc5bbad895c3d163256b4bc25 # v2
      with:
        melos-version: ${{ steps.melos.outputs.result }}
        run-bootstrap: true
    - name: Install others
      shell: bash
      run: melos prepare