include: ../../analysis_options.yaml

analyzer:
  plugins:
    - custom_lint

custom_lint:
  # Disable all lint rules depends on custom_lint.
  # enable_all_lint_rules: false
  rules:
    # Disable particular lint rules if you want ignore them whole package.
    # - unnecessary_rebuilds_from_media_query: false
