plugins:
  nilts:
    path: ../../packages/nilts
  nilts_clock:
    path: ../../packages/nilts_clock
  nilts_flutter_hooks:
    path: ../../packages/nilts_flutter_hooks

formatter:
  trailing_commas: preserve
