name: Setup Bun 🔧
description: Setup Bun

runs:
  using: 'composite'
  steps:
    - name: Setup Bun
      uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2.2.0

    - name: Setup Takumi Guard
      uses: flatt-security/setup-takumi-guard-npm@8f53b50568e4466f2d92504f349c05b9ffcb8b59 # v1

    - name: Bun Install
      shell: bash
      run: bun i --frozen-lockfile --ignore-scripts
