name: Setup Bun 🔧
description: Setup Bun

runs:
  using: 'composite'
  steps:
    - name: Setup Bun
      uses: oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76

    - name: Bun Install
      shell: bash
      run: bun i --frozen-lockfile --ignore-scripts
