name: Setup Bun 🔧
description: Setup Bun

runs:
  using: 'composite'
  steps:
    - name: Setup Bun
      uses: oven-sh/setup-bun@635640504f6d7197d3bb29876a652f671028dc97

    - name: Bun Install
      shell: bash
      run: bun i --frozen-lockfile --ignore-scripts
