name: Auto assign ✌️

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  assign:
    if: |
      github.event.pull_request.user.type == 'User'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    timeout-minutes: 5
    steps:
      - uses: actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410 # v6
        with:
          script: |
            const assignees = context.payload.pull_request.assignees
            if (!assignees || assignees.length === 0) {
              github.rest.issues.addAssignees({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                assignees: `${{ github.actor }}`,
              })
            }
